server:
  port: 9090

spring:
  application:
    name: authentication-service

  datasource:
#    url: jdbc:mysql://localhost:3306/nexo
#    username: root
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  hibernate:
    ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nexo76986@gmail.com
    password: wizxuwxkgjqhloqk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
    registerWithEureka: true
    fetchRegistry: true

jwt:
  secret: e07042972c539f933588c40f3f0c5620c335c3687b6dadd6aac1f191c1b04d0a
  expiration: 86400
