# Server
server:
  port: 8083

  # Spring
spring:
  application:
    name: discovery-service

  # Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
    registerWithEureka: false
    fetchRegistry: false
